;Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
;1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

mov rc,999     ; counter
mov rs,0       ; total sum
loop:
    jz break,rc    ; if rc == 0 >= break

    mod r1,rc,3   ; r1 = rc % 3
    mod r2,rc,5   ; r2 = rc % 5
    mul r3,r1,r2  ; r3 = r1 * r2

    jnz end_of_loop,r3    ; if r3 != 0 => end_of_loop

    add rs,rs,rc  ; rs = rs + rc

    end_of_loop:
        dec rc      ; rc = rc - 1
        jmp loop
break:
    halt