;Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
;1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

mov r1, 1
mov r2, 2   ; first 2 Fibonacci arguments
mov rs, r2  ; total sum
mov rc, 4000000 ; counter

loop:
    sub r3, rc, r2
    js break, r3    ; if r3 < 0 --> break
    add r3, r1, r2
    mod r4, r3, 2   ; r3 % 2
    jnz add_new_member, r4  ; if (r3 % 2) != 0 --> continue

    add rs, rs, r3 ; else sum += r3

    add_new_member:
        mov r1, r2
        mov r2, r3

    jmp loop

break:
    hlt